### PR TITLE
Change API to app.use

### PR DESCRIPTION
**Pull request by roberttod**
**IMPORTANT** this PR cannot be merged until all the dependant repos use the new API.
- Change API to app.use
- Add tests
- Add Makefile and .gitignore
- Improve readme
- Respond with the text 'ok'

I just copy+pasted the koa-status repo into this repo and made a few small changes so sorry if I nuked the history a bit.

I will publish this branch to npm once everyone reviews it.

### CODE REVIEW

**Comment by roberttod** [comment]
@KidkArolis @alanclarke

**Comment by jhollingworth** [comment]
What does this new API give us?

**Comment by roberttod** [comment]
It's a more standard way of doing it - we are open sourcing this project so I thought it would be pertinent to make it as standard as possible. I could keep backwards compatibility but @alanclarke and I agreed that supporting so many different methods of applying it was bad.

It is a lot of effort to update repos just to make a tiny improvement in the API - but we need to put this on NPM to get proper versioning and other benefits and at the moment the way of applying the middleware seems a bit odd.

**Comment by jhollingworth** [comment]
Completely agree with you about not maintaining multiple interfaces. However, considering we have [26 services which rely on the existing interface](https://github.com/search?l=&p=1&q=express-status+user%3Aqubitdigital+extension%3A.json&ref=advsearch&type=Code&utf8=%E2%9C%93) I'd argue it would be more pragmatic in this case to support both APIs. Especially since we're not using semver at all in any of those references.

I know we *could* go and update every single service but it seems like a lot of effort for little value...

**Comment by roberttod** [comment]
I get where you are coming from, it seems a bit drastic... we should however get those libraries using the npm version of this lib anyway so that they do have versioning, in which case we may as well use the new api.

I would be happy to do it over the weekend or something, just need to make the PR's and could probably just deploy the changes whenever instead of straight away. It makes me happier that our opensource stuff is as nice as possible though practically this doesn't really make much of a difference.

**Comment by jhollingworth** [comment]
I'd prefer to have a new repo with the new API and we add a console.warn to this library to tell people to use the other library. I'm massively against us making these sorts of breaking. 

Also, why are we open sourcing a simple get request?

**Comment by jhollingworth** [comment]
React have a very good approach to this. If there will be breaking changes, they will warn about the breaking change for one release and then make the actual breaking change in the next. This gives people an opportunity to upgrade at their own pace.

**Comment by roberttod** [comment]
How about I put it on npm at version `0.0.1` using the old API and I update all the repos to read from npm rather that the repo. Then I will update to the new API and release `1.0.0` thus not making anything break?

**Comment by jhollingworth** [comment]
OK, thats fine with me

**Comment by jhollingworth** [comment]
You didn't ask my other question though. Why are we open sourcing a simple get request? You're causing a load of work and I don't know why.

**Comment by roberttod** [comment]
- It's a very small and generic module that we have found useful here
- Putting it on NPM gives us versioning
- Having it as a private module causes some headaches for CI/Infra (this is the reason I am doing it now - there is some setup involved including private repos in my package.json and this is the only private repo I had)

**Comment by roberttod** [comment]
Actually - I had originally suggested that we create a new repo instead of moving this over but @alanclarke didn't want to create confusion by having 2 repos. Don't mind doing either way.

**Comment by KidkArolis** [comment]
So - I didn't read the whole discussion, but it's fine to merge this - nothing is affected since all of those services use npm shrinkwrap - so we can update one by one if we want to. And if you don't want to - you can also point to an older git commit. So totally no problems there!

Also - I've never been a fan of this service since it's easy to add a status route to any project in just 3 lines of code anyways.

**Pull request closed without merging**
